---
- hosts: ocp
  name: Prepare Keys

  tasks:
    - name: Add authorized key
      authorized_key:
        user: cloud-user
        state: present
        key: '{{ item }}'
      with_file:
        - "{{ bastion_public_key }}"

    - name: Configure bastion
      block:
        - name: Copy private key to bastion
          copy:
            src: "{{ bastion_private_key }}"
            dest: "/root/.ssh/id_rsa"
            mode: 0600

        - name: Copy public key to bastion
          copy:
            src: "{{ bastion_public_key }}"
            dest: "/root/.ssh/id_rsa.pub"
            mode: 0644
            
      when: (bastion is defined) and bastion