---
- hosts: openwrt
  name: Config Nodes on OpenWrt DNS

  tasks:
    - name: Unregister hosts
      shell: >
        conf="$(cat /etc/config/dhcp)" ;
        echo "${conf/$(cat /etc/config/dhcp | grep -C 1 {{ item.public_hostname }})/}" > /etc/config/dhcp ;

        conf="$(cat /etc/config/dhcp)" ;
        echo "${conf/$(cat /etc/config/dhcp | grep -C 1 {{ item.hostname }})/}" > /etc/config/dhcp
      with_items: "{{ ocp.nodes }}"

    - name: Register hosts
      shell: >
        echo -e "config domain\n\toption name '{{ item.public_hostname }}'\n\toption ip '{{ item.external_ip }}'\n" >> /etc/config/dhcp ;
        echo -e "config domain\n\toption name '{{ item.hostname }}'\n\toption ip '{{ item.internal_ip }}'\n" >> /etc/config/dhcp ;
      with_items: "{{ ocp.nodes }}"

    - name: Register console
      shell: >
        echo -e "config domain\n\toption name '{{ ocp.public }}'\n\toption ip '{{ ocp.console_ip }}'\n" >> /etc/config/dhcp ;

    - name: Register router
      lineinfile:
        path: /etc/dnsmasq.conf
        regexp: "address=/.{{ ocp.subdomain }}/.+"
        line: address=/.cloud.devnull.tools/{{ ocp.router_ip }}

    - name: Restart DNSmasq service
      openwrt_init:
        state: restarted
        name: dnsmasq
