---
- hosts: ocp
  name: Configure Installed Openshift

  tasks:
    - block:
      - name: Give cluster-admin access to defined user
        shell: >
          oc adm policy add-cluster-role-to-user cluster-admin {{ ocp.cluster_admin_user }}
      when: (bastion is defined) and bastion
