---
- hosts: ocp
  name: Prepare OpenShift Nodes

  tasks:
    - name: Subscribe host
      redhat_subscription:
        state: present
        username: "{{ subscription.user }}"
        password: "{{ subscription.password }}"
        pool_ids: "{{ subscription.pool_ids }}"

    - name: Disable all repositories
      shell: subscription-manager repos --disable=*

    - name: Enable repos
      shell: subscription-manager repos --enable={{ item }}
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ose-3.7-rpms
        - rhel-7-fast-datapath-rpms

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python2-setuptools
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - atomic-openshift-utils
        - docker

    - name: Update packages
      yum:
        name: '*'
        state: latest

    - name: Add authorized key
      authorized_key:
        user: cloud-user
        state: present
        key: '{{ item }}'
      with_file:
        - "{{ bastion_public_key }}"

    - name: Ensure openstack hostname
      shell: hostname {{ openstack_servername }} && echo "{{ openstack_servername }}" > /etc/hostname

    - name: Configure docker storage
      block:
        - name: Stop docker service
          systemd:
            state: stopped
            enabled: no
            name: docker

        - name: Remove /var/lib/docker directory
          file:
            path: /var/lib/docker
            state: absent

        - name: Copy docker-storage-setup file
          template:
            src: docker-storage-setup.j2
            dest: /etc/sysconfig/docker-storage-setup

        - name: Reset docker storage setup
          shell: docker-storage-setup --reset

        - name: Setup docker storage
          shell: docker-storage-setup

        - name: Start and enable docker service
          systemd:
            state: started
            enabled: yes
            name: docker

    - name: Configure bastion
      block:
        - name: Copy private key
          copy:
            src: "{{ bastion_private_key }}"
            dest: "/root/.ssh/id_rsa"
            mode: 0600

        - name: Copy public key
          copy:
            src: "{{ bastion_public_key }}"
            dest: "/root/.ssh/id_rsa.pub"
            mode: 0644

        - name: Copy ansible inventory file
          template:
            src: hosts-all-in-one.j2
            dest: /etc/ansible/hosts

        - name: Disable ansible host key checking
          lineinfile:
            path: /etc/ansible/ansible.cfg
            regexp: "^#host_key_checking = False"
            line: "host_key_checking = False"
            
        - name: Increase ansible timeout
          lineinfile:
            path: /etc/ansible/ansible.cfg
            regexp: "^#timeout = 10"
            line: "timeout = 30"

        - name: Patch openstack configuration file
          copy:
            src: openstack.conf.j2
            dest: /usr/share/ansible/openshift-ansible/roles/openshift_cloud_provider/templates/openstack.conf.j2
      when: bastion
