---
- hosts: ocp
  name: Prepare OpenShift Nodes

  tasks:
    - name: subscribe host
      redhat_subscription:
        state: present
        username: "{{ subscription.user }}"
        password: "{{ subscription.password }}"
        pool_ids: "{{ subscription.pool_ids }}"

    - name: disable all repositories
      shell: subscription-manager repos --disable=*

    - name: enable repos
      shell: subscription-manager repos --enable={{ item }}
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ose-3.7-rpms
        - rhel-7-fast-datapath-rpms

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python2-setuptools
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - atomic-openshift-utils
        - docker

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: add authorized key
      authorized_key:
        user: cloud-user
        state: present
        key: '{{ item }}'
      with_file:
        - "{{ bastion_public_key }}"

    - name: ensure openstack hostname
      shell: hostname {{ openstack_servername }} && echo "{{ openstack_servername }}" > /etc/hostname

    - name: add cloud provider configuration
      block:
        - file:
            path: /etc/origin/cloudprovider
            state: directory

        - template:
            src: cloud.conf.j2
            dest: /etc/origin/cloudprovider/openstack.conf

    - name: configure docker storage
      block:
        - systemd:
            state: stopped
            enabled: no
            name: docker

        - file:
            path: /var/lib/docker
            state: absent

        - template:
            src: docker-storage-setup.j2
            dest: /etc/sysconfig/docker-storage-setup

        - shell: docker-storage-setup --reset && docker-storage-setup

        - systemd:
            state: started
            enabled: yes
            name: docker

    - name: configure bastion
      block:
        - copy:
            src: "{{ bastion_private_key }}"
            dest: "/root/.ssh/id_rsa"
            mode: 0600

        - copy:
            src: "{{ bastion_public_key }}"
            dest: "/root/.ssh/id_rsa.pub"
            mode: 0644

        - template:
            src: hosts.j2
            dest: /etc/ansible/hosts

        - lineinfile:
            path: /etc/ansible/ansible.cfg
            regexp: "^#host_key_checking = False"
            line: "host_key_checking = False"
            
        - lineinfile:
            path: /etc/ansible/ansible.cfg
            regexp: "^#timeout = 10"
            line: "timeout = 30"
      when: bastion